그림장애물 삭제
bumsoft/Invaders-SDP pull request #16
Opened 2024-11-19 12:58 UTC by ppk052

업적메뉴는 이미 삭제되어있어서 그림장애물만 삭제했습니다! 검토부탁드립니다

2024-11-19 13:36 UTC, gimgibum21im reviewed
good

2024-11-19 13:43 UTC, saemmooll approved these changes
LGTM

2024-11-19 15:58 UTC, bumsoft requested changes
업적부분이 코어에서 엔트리포인트가 rank로만 변경된 상태라 업적스크린 메니저 등의 코드는 남아있는 상태입니다! 이부분도 제거 부탁드립니다

2024-11-20 11:54 UTC, ppk052 commented
코멘트 반영했습니다 확인해주세요

2024-11-20 12:00 UTC, bumsoft approved these changes
LGTM

2024-11-20 12:04 UTC, merged